# Ref:
#  (1) https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#about-yaml-syntax-for-issue-forms
#  (2) https://raw.githubusercontent.com/vercel/next.js/canary/.github/ISSUE_TEMPLATE/3.feature_request.yml
#  (3) https://raw.githubusercontent.com/aio-libs/aiohttp/master/.github/ISSUE_TEMPLATE/feature_request.yml
---
name: 🚀 Feature Request
description: Suggest a new feature for this project.
labels: 'template: feature'
body:
- type: markdown
  attributes:
    value: |
      **Thanks for taking a minute to file a feature for deck-viewer!**

      Verify first that your issue is not [already reported on GitHub][issue search].

      _Please fill out the form below with as many precise
      details as possible._

      [issue search]: ../search?q=is%3Aissue&type=issues

- type: textarea
  attributes:
    label: Describe the feature you'd like to request
    description: A clear and concise description of what you want and what your use case is.
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [Adventure Cards Code of Conduct][CoC] first.

      [CoC]: https://github.com/Adventure-Cards/deck-viewer/CODE_OF_CONDUCT.md
    options:
    - label: I agree to follow the Adventure Cards Code of Conduct
      required: true
...